### ISSUE TITLE
Help on an alias with parameters shows misleading jinja delimiters

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/hubot-stackstorm#149]
I defined a chatops alias like that:
```yaml
name: "mypack_doc"
action_ref: "mypack.doc"
description: "Launch a documentation build & upload results on website."
formats:
  - "(doc|docs|dox|docu) {{branch=master}}"
```
and in the slack channel, when I ask for help, i get that:
```
stanleyAPP [6:08 PM] 
!(doc|docs|dox|docu) {{branch=master}} - Launch a documentation build & upload results on website.
```

I think the jinja delimiters `{{` and `}}` should be strippped from the help output, since they are misleading my users who just copy/paste them...

The `(|)` enabling choice, is less problematic to grasp, apparently...

WDYT ?
