### ISSUE TITLE
Support for "Button attachments"

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [StackStorm/hubot-stackstorm#151]
I am not able to send the message with button attachments. If I send simple message{non-attachment message} its working fine. If i send message with extra param from the stackstorm the message is not getting displayed in the channel.

If I have changed the line 137 in **post_data.js** under **lib** folder from **attachments: content**  to **attachments: content.attachments ? content.attachments : content** then the button gets displayed.

Please help on this issue. Is this a right fix

message from stackstorm
```yaml
action:
  ref: chatops.post_message
  parameters:
    channel: "bq97zw96ypnrjp15h9ey4bhu5o"
    #channel: "#town-square"
    message: "Trying button action"
    extra:
      color: "#ff0000"
      mattermost:
           attachments:
                 - pretext: "This is the attachment pretext."
                   text: "This is the attachment text."
                   actions:
                      - name: "Ephemeral Message"
                        integration:
                              url: "https://x.x.x.x/hubot/buttonaction"
                              context:
                                  action: "do_something_ephemeral"
                      - name: "Update"
                        integration:
                              url: "https://x.x.x.x/hubot/buttonaction"
                              context:
                                  action: "do_something_update"
```
