### ISSUE TITLE
Display formatting that contains []'s  {{ }}'s do not load into hubot

### ISSUE THREAD

**Issue by jjm** [StackStorm/hubot-stackstorm#94]
Just noticed an odd problem, the following display formatting works:

```yaml
formats:
  - display: "alertlogic scan list [<customer_id>]"
    representation:
      - "alertlogic scan list {{customer_id=0}}"
```

Which displays via hubot as:

```
! alertlogic scan list [<customer_id>] - List all the AlertLogic scans for a customer_id to account of key.
```
However if you combine `[ ]` with `{{var}}` as follows:

```yaml
formats:
  - display: "alertlogic scan list [{{customer_id}}]"
    representation:
      - "alertlogic scan list {{customer_id=0}}"
```

You get no aliases in Hubot and the hubot logs contain the following:

```
[Fri Mar 04 2016 15:11:42 GMT+0000 (UTC)] ERROR Failed to retrieve commands from "https://my-st2-server:443/api": Invalid regular expression: /alertlogic scan list [\s*([\s\S]+?)\s*](\s+(\S+)\s*=("([\s\S]*?)"|'([\s\S]*?)'|({[\s\S]*?})|(\S+))\s*)*$/: Unmatched ')'
```
It very much looks like parsing of display is happening when you include `{{ var }}` I've always done this as I was following the examples at https://stackstorm.com/2015/12/08/stackstorm-1-2-0-the-new-chatops/.

Jon.

**Comment by emedvedev** [comment]
Unrelated to the bug, wouldn't something like this work better for you instead of defaulting to `0`?

```
formats:
  - display: "alertlogic scan list [customer_id]"
    representation:
      - "alertlogic scan list"
      - "alertlogic scan list {{customer_id}}"
```
